apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: gitlab-backup
spec:
  schedule: "30 18 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: gitlab-backup
            image: govcloud/k8s-kubectl:v1.10.4
            command: ["/bin/sh"]
            env:
              - name: AZURE_STORAGE_ACCOUNT
                value: statcandata
              - name: AZURE_STORAGE_KEY
                valueFrom:
                  secretKeyRef:
                    name: azure-storage-statcandata
                    key: password
              - name: SLACK_CLI_TOKEN
                valueFrom:
                  secretKeyRef:
                    name: azure-slack-statscloud
                    key: password
            args:
            - -c
            - pod_name=$(kubectl get pods -n default -l name=gitlab-gitlab -o jsonpath='{.items[*].metadata.name}');
              kubectl exec $pod_name -n default -- gitlab-rake gitlab:backup:create SKIP=registry;
              backup_tar=$(kubectl exec $pod_name -- find /var/opt/gitlab/backups -maxdepth 1 -name '*gitlab_backup.tar' | sort -t_ -nk2,2 | tail -n1);
              kubectl cp default/$pod_name:$backup_tar .;
              az storage blob upload --account-name $AZURE_STORAGE_ACCOUNT
                --account-key $AZURE_STORAGE_KEY
                --container-name backups
                --type block
                --file $(basename $backup_tar)
                --name $(basename $backup_tar);
              kubectl exec $pod_name -n default -- rm $backup_tar;
              kubectl exec $pod_name -n default -- tar cfz /var/opt/gitlab/backups/$(date "+etc-gitlab-%s.tgz") -C / etc/gitlab;
              backup_secrets=$(kubectl exec $pod_name -- find /var/opt/gitlab/backups -maxdepth 1 -name 'etc-gitlab-*.tgz' | sort -t_ -nk2,2 | tail -n1);
              kubectl cp default/$pod_name:$backup_secrets .;
              az storage blob upload --account-name $AZURE_STORAGE_ACCOUNT
                --account-key $AZURE_STORAGE_KEY
                --container-name backups
                --type block
                --file $(basename $backup_secrets)
                --name $(basename $backup_secrets);
              kubectl exec $pod_name -n default -- rm $backup_secrets;
              slack chat send
                --author 'William Hearn'
                --author-icon 'https://s.gravatar.com/avatar/eca9a4ec0967837e98593484bf64424a?s=80'
                --author-link 'https://github.com/sylus'
                --channel '#ci'
                --color good
                --footer "${AZURE_STORAGE_ACCOUNT} -> $(basename $backup_tar)"
                --text 'The GitLab cronjob initiated by Kubernetes has completed successfully.'
                --title 'GitLab Backup'
                --title-link 'https://github.com/sylus';
          restartPolicy: OnFailure
